/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type {
  IERC1155MetadataURI,
  IERC1155MetadataURIInterface,
} from '../IERC1155MetadataURI';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'id',
        type: 'uint256',
      },
    ],
    name: 'uri',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class IERC1155MetadataURI__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155MetadataURIInterface {
    return new utils.Interface(_abi) as IERC1155MetadataURIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155MetadataURI {
    return new Contract(address, _abi, signerOrProvider) as IERC1155MetadataURI;
  }
}
