/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { OwnableMock, OwnableMockInterface } from "../OwnableMock";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "openFunction",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ownedFunction",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b0319163390811782556040519091907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0908290a36103708061005f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80633186ce2d1461005157806346be982e1461006e5780638da5cb5b14610076578063f2fde38b14610091575b600080fd5b6100596100a6565b60405190151581526020015b60405180910390f35b61005961010c565b6000546040516001600160a01b039091168152602001610065565b6100a461009f36600461030c565b610168565b005b600080546001600160a01b031633146101065760405162461bcd60e51b815260206004820181905260248201527f4f776e61626c653a2043616c6c6572206973206e6f7420746865206f776e657260448201526064015b60405180910390fd5b50600190565b600080546001600160a01b03163314156101065760405162461bcd60e51b815260206004820152601c60248201527f4f776e61626c653a2043616c6c657220697320746865206f776e65720000000060448201526064016100fd565b6000546001600160a01b031633146101c25760405162461bcd60e51b815260206004820181905260248201527f4f776e61626c653a2043616c6c6572206973206e6f7420746865206f776e657260448201526064016100fd565b6101cb816101ce565b50565b6000546001600160a01b031633146102285760405162461bcd60e51b815260206004820181905260248201527f4f776e61626c653a2043616c6c6572206973206e6f7420746865206f776e657260448201526064016100fd565b6001600160a01b0381166102a45760405162461bcd60e51b815260206004820152602660248201527f4f776e61626c653a204e6577206f776e657220697320746865207a65726f206160448201527f646472657373000000000000000000000000000000000000000000000000000060648201526084016100fd565b600080546001600160a01b038381167fffffffffffffffffffffffff0000000000000000000000000000000000000000831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b60006020828403121561031d578081fd5b81356001600160a01b0381168114610333578182fd5b939250505056fea2646970667358221220032f73c0348427593975e3b029cda2faf0526591dac33103dd31d93b113ea8d164736f6c63430008040033";

type OwnableMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OwnableMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OwnableMock__factory extends ContractFactory {
  constructor(...args: OwnableMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "OwnableMock";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<OwnableMock> {
    return super.deploy(overrides || {}) as Promise<OwnableMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): OwnableMock {
    return super.attach(address) as OwnableMock;
  }
  connect(signer: Signer): OwnableMock__factory {
    return super.connect(signer) as OwnableMock__factory;
  }
  static readonly contractName: "OwnableMock";
  public readonly contractName: "OwnableMock";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OwnableMockInterface {
    return new utils.Interface(_abi) as OwnableMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OwnableMock {
    return new Contract(address, _abi, signerOrProvider) as OwnableMock;
  }
}
