/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RoutableRouterMockInterface extends utils.Interface {
  contractName: "RoutableRouterMock";
  functions: {
    "openFunction()": FunctionFragment;
    "routedFunction()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "openFunction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routedFunction",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "openFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routedFunction",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RoutableRouterMock extends BaseContract {
  contractName: "RoutableRouterMock";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RoutableRouterMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    openFunction(overrides?: CallOverrides): Promise<[boolean]>;

    "openFunction()"(overrides?: CallOverrides): Promise<[boolean]>;

    routedFunction(overrides?: CallOverrides): Promise<[boolean]>;

    "routedFunction()"(overrides?: CallOverrides): Promise<[boolean]>;
  };

  openFunction(overrides?: CallOverrides): Promise<boolean>;

  "openFunction()"(overrides?: CallOverrides): Promise<boolean>;

  routedFunction(overrides?: CallOverrides): Promise<boolean>;

  "routedFunction()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    openFunction(overrides?: CallOverrides): Promise<boolean>;

    "openFunction()"(overrides?: CallOverrides): Promise<boolean>;

    routedFunction(overrides?: CallOverrides): Promise<boolean>;

    "routedFunction()"(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    openFunction(overrides?: CallOverrides): Promise<BigNumber>;

    "openFunction()"(overrides?: CallOverrides): Promise<BigNumber>;

    routedFunction(overrides?: CallOverrides): Promise<BigNumber>;

    "routedFunction()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    openFunction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "openFunction()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    routedFunction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "routedFunction()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
