name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: mkdir config
      - name: Create Config accounts json
        id: create-json
        uses: devops-actions/json-to-file@v1.0.0
        with:
          filename: 'config/accounts.json'
          json: ${{ secrets.ACCOUNTS }}
      - run: npm install
      - run: npm test
